### ISSUE TITLE
Variable name in 'find_vesicles.py'

### ISSUE THREAD

**Issue by JoshuaMHardy** [r-karimi/vesicle-picker#1]
I am trying out the find_vesicle.py script on some of my micrographs, and I received the following error:

> TypeError: preprocess_micrograph() missing 1 required positional argument: 'downsample'

When I changed the variable name from 'downsample_factor' to 'downsample' in line 60 of find_vesicles.py, it ran successfully.

**Comment by r-karimi** [comment]
Thanks so much for finding this! I just fixed it--marking the issue as closed. Let me know if you run into any more bugs!
