### ISSUE TITLE
filter_vesicles.py only does first 12 micrographs

### ISSUE THREAD

**Issue by JoshuaMHardy** [r-karimi/vesicle-picker#2]
I noticed that the filter script only does the first 12 micrographs. It looks like the script is currently configured only to process 12 micrographs:

Line 33:
for micrograph in tqdm(micrographs[0:12]):

Should be:
for micrograph in tqdm(micrographs[:]):

**Comment by r-karimi** [comment]
Thanks for the catch @joshhardywehi! I'll push an update shortly.
